axon:
  axonserver:
    servers: ${AXON_SERVERS:localhost}

server:
  port: ${PORT:8082}

spring:
  application:
    name: shipping-service
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.bwg.shippingservice: ${APP_LOG_LEVEL:info}
