axon:
  axonserver:
    servers: ${AXON_SERVERS:localhost}

server:
  port: ${PORT:8082}

spring:
  application:
    name: shipping-service

  jpa:
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.bwg.shippingservice: ${APP_LOG_LEVEL:info}

---

spring:
  profiles: postgresql
  
  jpa:
    generate-ddl: true # PostgreSQL 사용시에도 axon 엔티티를 생성하도록 true 셋팅
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  # using properties of spring-cloud-config server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: false
