axon:
  axonserver:
    servers: ${AXON_SERVERS:localhost}

server:
  port: ${PORT:8080}

spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.bwg.orderservice: ${APP_LOG_LEVEL:info}

---

spring:
  profiles: postgresql
  
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  # using properties of spring-cloud-config server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: false
