axon:
  axonserver:
    servers: ${AXON_SERVERS:localhost}

server:
  port: ${PORT:8080}

spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.bwg.orderservice: ${APP_LOG_LEVEL:info}
