---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: payment-repository
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bxm-cloud
    bxm.io/corporation: bwg
  name: payment-repository
spec:
  ports:
  - port: 5432
    name: http
    targetPort: postgresql
  selector:
    app.kubernetes.io/instance: payment-repository
    app.kubernetes.io/component: database
    bxm.io/corporation: bwg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: payment-repository
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bxm-cloud
    bxm.io/corporation: bwg
  name: payment-repository
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: payment-repository
      app.kubernetes.io/component: database
      bxm.io/corporation: bwg
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: payment-repository
        app.kubernetes.io/version: 0.1.0
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: bxm-cloud
        bxm.io/corporation: bwg
    spec:
      containers:
        - image: postgres:10.5-alpine
          name: postgresql
          volumeMounts:
            - mountPath: "/data"
              name: postgresql-vol
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: repository
                  key: payment.database.db
      volumes:
        - name: postgresql-vol
          persistentVolumeClaim:
            claimName: postgresql
      restartPolicy: Always
