---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bxm-cloud
    bxm.io/corporation: bwg
  name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
