---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: order-secret
    app.kubernetes.io/instance: order-secret
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: bxm-cloud
    bxm.io/corporation: bwg
  name: order-secret
type: Opaque
data:
  # echo -n 'order' | base64
  username: b3JkZXI=
  # echo -n 'redro' | base64
  password: cmVkcm8=
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: payment-secret
    app.kubernetes.io/instance: payment-secret
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: bxm-cloud
    bxm.io/corporation: bwg
  name: payment-secret
type: Opaque
data:
  # echo -n 'payment' | base64
  username: cGF5bWVudA==
  # echo -n 'tnemyap' | base64
  password: dG5lbXlhcA==
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: shipping-secret
    app.kubernetes.io/instance: shipping-secret
    app.kubernetes.io/version: 0.1.0
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: bxm-cloud
    bxm.io/corporation: bwg
  name: shipping-secret
type: Opaque
data:
  # echo -n 'shipping' | base64
  username: c2hpcHBpbmc=
  # echo -n 'gnippihs' | base64
  password: Z25pcHBpaHM=